In [8]:
import pandas as pd
from pathlib import Path

In [9]:
# Load in file
# Store filepath in a variable
titles_data_csv = Path("titles.csv")
credits_data_csv = Path("credits.csv")

In [10]:
titles_data_df= pd.read_csv(titles_data_csv)
credits_data_df = pd.read_csv(credits_data_csv)

In [15]:
merged_movie_data_df = pd.merge(titles_data_df, credits_data_df, on = "id", how = "outer")
merged_movie_data_df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score,person_id,name,character,role
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,tt0850645,8.6,1092.0,15.424,7.6,59401.0,Joe Besser,Joe,ACTOR
1,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,tt0850645,8.6,1092.0,15.424,7.6,31460.0,Moe Howard,Moe,ACTOR
2,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,tt0850645,8.6,1092.0,15.424,7.6,31461.0,Larry Fine,Larry,ACTOR
3,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,tt0017925,8.2,89766.0,8.647,8.0,21174.0,Buster Keaton,Johnny Gray,ACTOR
4,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,tt0017925,8.2,89766.0,8.647,8.0,28713.0,Marion Mack,Annabelle Lee,ACTOR

In [29]:
columns_to_delete= ['description','age_certification','runtime','imdb_id','imdb_votes']
merged_movie_data_df.drop(columns=columns_to_delete)

,id,title,type,release_year,genres,production_countries,seasons,imdb_score,tmdb_popularity,tmdb_score,person_id,name,character,role
0,ts20945,The Three Stooges,SHOW,1934,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,8.6,15.424,7.6,59401.0,Joe Besser,Joe,ACTOR
1,ts20945,The Three Stooges,SHOW,1934,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,8.6,15.424,7.6,31460.0,Moe Howard,Moe,ACTOR
2,ts20945,The Three Stooges,SHOW,1934,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,8.6,15.424,7.6,31461.0,Larry Fine,Larry,ACTOR
3,tm19248,The General,MOVIE,1926,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,8.2,8.647,8.0,21174.0,Buster Keaton,Johnny Gray,ACTOR
4,tm19248,The General,MOVIE,1926,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,8.2,8.647,8.0,28713.0,Marion Mack,Annabelle Lee,ACTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125349,tm1054116,Baikunth,MOVIE,2021,"['family', 'drama']",[],NaN,8.4,0.645,NaN,1938565.0,Vijay Thakur,Sanjay Thakur,ACTOR
125350,tm1054116,Baikunth,MOVIE,2021,"['family', 'drama']",[],NaN,8.4,0.645,NaN,728899.0,Vanya Wellens,Budhiya,ACTOR
125351,tm1054116,Baikunth,MOVIE,2021,"['family', 'drama']",[],NaN,8.4,0.645,NaN,1938620.0,Vishwa Bhanu,Gissu,ACTOR
125352,tm1054116,Baikunth,MOVIE,2021,"['family', 'drama']",[],NaN,8.4,0.645,NaN,1938620.0,Vishwa Bhanu,NaN,DIRECTOR
125353,ts275838,Waking Up Eighty,SHOW,2021,['drama'],[],1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
merged_movie_data_df.count()

id                      125354
title                   125354
type                    125354
description             125163
release_year            125354
age_certification        56857
runtime                 125354
genres                  125354
production_countries    125354
seasons                   8501
imdb_id                 119978
imdb_score              118987
imdb_votes              118957
tmdb_popularity         124800
tmdb_score              114263
person_id               124347
name                    124347
character               108040
role                    124347
dtype: int64